import axiosInstance from '@/lib/axios'
import type {
  CreateNotificationRequest,
  Notification,
  PagedResult,
  PaginationQuery,
} from '@/types'

/**
 * Fetch the authenticated user's notifications, newest first.
 */
export async function getMyNotifications(
  params?: PaginationQuery & { unreadOnly?: boolean },
): Promise<PagedResult<Notification>> {
  const { unreadOnly, ...rest } = params ?? {}
  const response = await axiosInstance.get<PagedResult<Notification>>(
    '/notifications/my',
    {
      params: {
        ...rest,
        ...(unreadOnly !== undefined ? { isRead: !unreadOnly } : {}),
      },
    },
  )
  return response.data
}

/**
 * Create a notification (admin / system use; regular users typically only
 * receive notifications generated by the backend).
 */
export async function createNotification(
  data: CreateNotificationRequest,
): Promise<Notification> {
  const response = await axiosInstance.post<Notification>(
    '/notifications',
    data,
  )
  return response.data
}

/**
 * Mark a single notification as read.
 */
export async function markAsRead(id: string): Promise<Notification> {
  const response = await axiosInstance.patch<Notification>(
    `/notifications/${id}/read`,
  )
  return response.data
}

/**
 * Mark every unread notification for the current user as read.
 */
export async function markAllRead(): Promise<{ count: number }> {
  const response = await axiosInstance.patch<{ count: number }>(
    '/notifications/read-all',
  )
  return response.data
}

/**
 * Permanently delete multiple notifications by their IDs.
 */
export async function bulkDeleteNotifications(
  ids: string[],
): Promise<{ count: number }> {
  const response = await axiosInstance.delete<{ count: number }>(
    '/notifications/bulk',
    { data: { ids } },
  )
  return response.data
}
